CREATE TABLE IF NOT EXISTS CLIENT
(
    ID       NUMBER NOT NULL PRIMARY KEY,
    PASSWORD NUMBER NOT NULL
);

CREATE TABLE IF NOT EXISTS CARD
(
    ID      NUMBER NOT NULL,
    CLIENT  NUMBER NOT NULL,
    BALANCE NUMBER,
    NUMBER  NUMBER NOT NULL,
    TITLE   VARCHAR(300),
    FOREIGN KEY (client) REFERENCES CLIENT (Id)
);